using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace API.SumUps.UserSumUps;

public class UserSumUpDocument(UserSumUpModel model) : IDocument
{
    public DocumentMetadata GetMetadata()
    {
        return DocumentMetadata.Default;
    }

    public DocumentSettings GetSettings()
    {
        return DocumentSettings.Default;
    }

    public void Compose(IDocumentContainer container)
    {
        container
            .Page(descriptor =>
            {
                descriptor.Margin(50);

                descriptor.Header().Element(ComposeHeader);
                descriptor.Content().Element(ComposeContent);
                descriptor.Footer().Height(50).Background(Colors.Grey.Lighten1);
            });
    }

    private void ComposeContent(IContainer obj)
    {
        obj
            .PaddingVertical(40).Column(column =>
            {
                column.Spacing(5);
                column.Item().Element(ComposeGroupDetails);
            });
    }

    private void ComposeGroupDetails(IContainer obj)
    {
        obj.Column(column =>
        {
            column.Item().Text(text =>
            {
                text.Span("Group Details").Style(TextStyle.Default.FontSize(20).SemiBold());
            });
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                });

                table.Header(header =>
                {
                    header.Cell().Element(CellStyle).Text("Group Name");
                    header.Cell().Element(CellStyle).Text("Balance");
                    header.Cell().Element(CellStyle).Text("Amount Due");
                    header.Cell().AlignRight().Element(CellStyle).Text("To User");

                    static IContainer CellStyle(IContainer obj)
                    {
                        return obj.DefaultTextStyle(x => x.SemiBold()).PaddingVertical(5).BorderBottom(1)
                            .BorderColor(Colors.Black);
                    }
                });

                foreach (var groupInfo in model.GroupInfos)
                {
                    table.Cell().Element(CellStyle).Text(groupInfo.GroupName);
                    table.Cell().Element(CellStyle).Text(groupInfo.Balance.ToString("0.00"));
                    table.Cell().Element(CellStyle).Text(groupInfo.AmountDue.ToString("0.00"));
                    table.Cell().AlignRight().Element(CellStyle).Text(groupInfo.ToUserName ?? "-");

                    static IContainer CellStyle(IContainer container)
                    {
                        return container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);
                    }
                }
            });
        });
    }

    private void ComposeHeader(IContainer obj)
    {
        var titleStyle = TextStyle.Default.FontSize(20).SemiBold().FontColor(Colors.Blue.Medium);
        obj.Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text($"\"{model.UserName}\" user").Style(titleStyle);
                column.Item().Text(text =>
                {
                    text.Span("Generated on ").Style(TextStyle.Default.FontSize(10));
                    text.Span($"{model.CurrentDate:dd.MM.yyyy}").Style(TextStyle.Default.FontSize(10).SemiBold());
                });
                column.Item().Text(text =>
                {
                    text.Span("Proudly generated by ").Style(TextStyle.Default.FontSize(10));
                    text.Span("MoneyMinder")
                        .Style(TextStyle.Default.FontSize(10).SemiBold().FontColor(Colors.Blue.Medium));
                });
            });
            row.ConstantItem(100).Height(50).AlignRight().Element(ComposeLogo);
        });
    }

    private void ComposeLogo(IContainer obj)
    {
        obj.Image("wwwroot/favicon.ico").FitArea();
    }
}