networks:
  default:
  local:

services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      # DATABASE
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      
      # API
      API_ENDPOINT: ${API_ENDPOINT}
      
      # GOOGLE_AUTHENTICATION
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      
      # CLIENT
      CLIENT_URL: ${CLIENT_URL}
    
    networks:
      - default
      - local
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: postgres:alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - local
    #  dev only:
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5