networks:
    default:
    local:

services:
    api:
        image: api
        build:
            context: .
            dockerfile: API/Dockerfile
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            DB_PORT: ${DB_PORT}
            API_ENDPOINT: ${API_ENDPOINT}
        networks:
            - default
            - local
        ports:
            - "${API_PORT}:8080"
        depends_on:
            - db
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - local
#  dev only:
        ports:
            - "${DB_PORT}:5432"

