networks:
  default:
  local:

services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      # DATABASE
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      
      # API
      API_ENDPOINT: ${API_ENDPOINT}
      JWT_SECRET: ${JWT_SECRET}
      API_PORT: ${API_PORT}
      
      # GOOGLE_AUTHENTICATION
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      
      # FTP
      PASV_ADDRESS: ${PASV_ADDRESS}
      # JUSTIFICATIONS
      FTP_JUSTIFICATIONS_USER: ${FTP_JUSTIFICATIONS_USER}
      FTP_JUSTIFICATIONS_PASS: ${FTP_JUSTIFICATIONS_PASS}
      # AVATARS
      FTP_AVATARS_USER: ${FTP_AVATARS_USER}
      FTP_AVATARS_PASS: ${FTP_AVATARS_PASS}
      
      # CLIENT
      CLIENT_URL: ${CLIENT_URL}
    
    networks:
      - default
      - local
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  db:
    image: postgres:alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - local
    #  dev only:
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  cache:
    image: redis:alpine
    networks:
      - local
    ports:
      - "${CACHE_PORT}:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: ${FTP_JUSTIFICATIONS_USER}|${FTP_JUSTIFICATIONS_PASS}|/home/vsftpd/justifications|| ${FTP_AVATARS_USER}|${FTP_AVATARS_PASS}|/home/vsftpd/avatars||
      ADDRESS: ${PASV_ADDRESS}
    volumes:
      - ./ftp_data:/home/vsftpd
    networks:
      - local
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "ftp://localhost:21" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5

volumes:
  dbdata: