# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/home/papylols/aC#_Projects/3PROJ-BACK"
      dockerfile: "API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/API.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "api:dev"
    ports:
    - "127.0.0.1:57023:57100"
    - "127.0.0.1:57223:57300"
    volumes:
    - "/home/papylols/.nuget/packages:/home/app/.nuget/packages"
    - "/home/papylols/aC#_Projects/3PROJ-BACK/API:/app:rw"
    - "/home/papylols/aC#_Projects/3PROJ-BACK:/src:rw"
    - "/home/papylols/.local/share/JetBrains/RiderRemoteDebugger/2023.3.3/Linux64:/opt/rider-debugger"
    - "/home/papylols/.local/share/JetBrains/Toolbox/apps/rider/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/home/papylols/.cache/JetBrains/Rider2023.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2024_2_09_19_57_51:/var/opt/rider-debugger:rw"
    working_dir: "/app"
